name: Template UI
language: nodejs
variables:
  - name: bearer_token
    inputType: FreeText
    description: ''
    defaultValue: pat-087fb05b72df4e91b8eff7712e409965
    required: false
  - name: Deployment__Id
    inputType: FreeText
    description: ''
    defaultValue: 763a4d65-f3a5-4f10-8d86-bd83d93c959e
    required: false
  - name: offers_topic
    inputType: InputTopic
    description: ''
    defaultValue: special-offers
    required: false
  - name: click_topic
    inputType: OutputTopic
    description: ''
    defaultValue: click-data
    required: false
dockerfile: src/build/dockerfile
defaultFile: src/app/services/quix.service.ts
